# Generated by Django 4.1.13 on 2026-02-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_imageset_zip_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
